# Custom vars
author:
    name: 'Darren Lee'
    url: "http://darrensdesign.com" # the base hostname & protocol for your site, e.g. http://example.com
    email: 'me@darrensdesign.com'
title: Darren's Design
description: > # this means to ignore newlines until "baseurl:"
  Darren's Design - portfolio website sharing latest works, design tips, and learnings
baseurl: "/" # the subpath of your site, e.g. /blog
twitter_username: iamdarrenly
github_username:  darrenleeyong
twitter:
    username: iamdarrenly
logo: /images/favicon.png 
image: https://darrensdesign.com/images/about/pinkwall.jpg 

future: true
excerpt_separator: '---'

sass:
    style: compressed
collections:
    docs: {output: true, permalink: '/docs/:path/'}
    portfolio: {output: true, permalink: '/portfolio/:path/'}
    projects: {output: true, permalink: '/projects/:path/'}
defaults:
    - {scope: {type: docs}, values: {layout: docs}}
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:year/:month/:day/:title'}}
    - {scope: {path: ""}, values: {image: {path: /images/opengraph.png, width: 1200, height: 630}}}
exclude:
    - node_modules
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - package.json
    - script
    - spec
    - _drafts
include:
    - _pages
    - _projects
    - .htaccess

# Paginate
paginate: 8
paginate_path: "/blog/page:num/"
permalink:     '/blog/:year/:title/'

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-paginate
    - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

